Issue/241 native zip
LLK/scratchjr pull request #404
Opened 2021-04-09 13:56 UTC by yueyuzhao

### Resolves

rewrite import/export with native code

Fix #241 

### Proposed Changes

1. iOS: rewrite import/export
2. Android: rewrite import/export
3. JavaScript: remove import and export codes

### Reason for Changes

Importing and exporting in JavaScript is slow and may crash when handling large project with lots of sounds. 

### Test Coverage

[ ] iOS: import project from `Files` app
[ ] iOS: import project from email
[ ] iOS: export project using email
[ ] iOS: export project using airdrop
[ ] Android: import project from folder
[ ] Android: import project from email
[ ] Android: export project using email

2021-04-09 13:57 UTC, yueyuzhao commented
This will also fix #372

2021-04-27 14:19 UTC, chrisgarrity commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/ScratchJrUtil.java
> +            sourceFile.delete();
This is in the android code, and I haven't started testing that yet, but should it really be deleting the sourceFile here? I was expecting it to check the toLocation and remove anything that existed there.

2021-04-27 22:10 UTC, yueyuzhao commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/ScratchJrUtil.java
> +            sourceFile.delete();
Hi @chrisgarrity , you are right! The `toLocation` other than `sourceFile` here should be cleaned, but `FileOutputStream` later will overwrite the `toLocation` file if exists, so we needn't delete it mannually. 
BWT `sourceFile` is a folder and can't be deleted if there are files still in it, so it has no effect on zipping.

2021-04-29 16:42 UTC, chrisgarrity requested changes
Sorry that took so long. I've left a few suggestions, let me know if you have questions about any of them. The major thing is that reviewing this change made me realized that there are a couple of problems that are related, but that shouldn't hold up this PR. I will write up issues for them.

2021-04-29 17:09 UTC, chrisgarrity commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/ScratchJrUtil.java
> +        byte[] buf = new byte[1024];
should this be BUFFER_SIZE as well, or is there a reason for it to be 1024?

2021-04-29 23:08 UTC, yueyuzhao commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/ScratchJrActivity.java
> +                    e.printStackTrace();
Hi @chrisgarrity , it's definitely better if we can send a notification to the user that the import failed, we can simply `Toast.makeText(ScratchJrActivity.this, "Import project failed", Toast.LENGTH_LONG);`, but I don't want to do that way right now. Ideally we send the result to JavaScript and it will show an alert box with messages that are in user selected languages.

2021-04-30 11:37 UTC, yueyuzhao commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/IOManager.java
> +        projectJson.put("version", "iOSv01");
Hi @chrisgarrity , I think we should treat `version` field as the project json structure version, if we want to track user's device when they sharing, we'd better add a new field other than place it in the `version` field.

2021-04-30 11:45 UTC, yueyuzhao commented on ios/ScratchJr/src/IO.m
> +            [asset setValue:[sprite valueForKey:@"id"] forKey:@"name"];
Sorry, but I don't think so. If we couldn't find the sprite in the project JSON, we can't know its name or size, and neither shall we make the thumb for the sprite, nor need we insert it to the database.

2021-04-30 11:48 UTC, yueyuzhao commented on ios/ScratchJr/src/IO.m
> +            continue;
I'll do some refactor to this method to make this more readable and easier to understand.

2021-04-30 13:05 UTC, yueyuzhao commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/IOManager.java
> +            asset.put("version", "iOSv01");
After some tests, we can't skip this field right now, JavaScript is querying library assets with this field like this:
```javascript
var json = {};
json.cond = 'ext = ? AND version = ?';
json.items = ((type == 'costumes') ?
    ['md5', 'altmd5', 'name', 'scale', 'width', 'height'] : ['altmd5', 'md5', 'width', 'height']);
json.values = ['svg', ScratchJr.version];
json.order = 'ctime desc';
```

2021-04-30 13:35 UTC, yueyuzhao commented
### Test Coverage

- [x]  iOS: import project from `Files` app
- [x]  iOS: import project from email
- [x]  iOS: export project using email
- [x]  iOS: export project using airdrop
- [x]  Android: import project from folder
- [x]  Android: import project from email
- [x]  Android: export project using email
- [x]  eslint without errors

2021-05-03 20:59 UTC, chrisgarrity commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/IOManager.java
> +        projectJson.put("version", "iOSv01");
Yes, I'm coming to that conclusion too, and I suppose that the structure of the project json hasn't changed since iOSv01, so it kind of makes sense.

2021-05-03 21:00 UTC, chrisgarrity commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/ScratchJrActivity.java
> +                    e.printStackTrace();
👍

2021-05-03 21:08 UTC, chrisgarrity commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/IOManager.java
> +            asset.put("version", "iOSv01");
Interesting, I think this is how it distinguishes between library content and user-generated content to display user generated thumbnails at the top of the library. As far as I know the actual library assets do not set a version.

2021-05-03 21:25 UTC, chrisgarrity approved these changes
Thank you for those changes. The refactor of the IO.m file is very helpful!

2021-05-03 21:35 UTC, merged