fix story saving for PBS
LLK/scratchjr pull request #428
Opened 2021-05-26 21:27 UTC by yueyuzhao

### Resolves

This fixes https://github.com/LLK/scratchjr-private/issues/597 

### Proposed Changes

make `currentProject` can be set outside of `ScratchJr.js`

### Reason for Changes

Without this setter method, we couldn't save the story project 

### Test Coverage

- [ ] don't save story project without changing
- [ ] Works well for PBS version
- [ ] lint the code

2021-05-28 13:41 UTC, yueyuzhao commented
- [ ] Don't save story starters project if not changed.
- [ ] Don't save story starters project if only the title changed.
- [ ] Can't share the story starters if not changed.
- [ ] Can close the info dialog after open

2021-07-30 20:58 UTC, chrisgarrity requested changes
There are some issues with translating the story starter name if you're not in English, otherwise this looks much better. 

Right now if you switch the interface into Spanish, the name of "Showtime" changes to "Luz Camara, Acción"
* if you make changes to the story starter and go back to the lobby, the name is "Luz, Camara, Acción 1" as expected
* if you make changes to the story starter, then open project info, the name appears as "Showtime!" not "Luz, Camara, Acción", and when you return to the lobby the name is "Showtime!" , it should be "Luz, Camara, Acción 1"
* if you open a story starter and immediately open project info and change the name to something else (e.g. "Surprise", then make changes so that the project is saved. The name of the project in the lobby is "String Missing: SAMPLE_Surprise", it should be "Surprise"

2021-07-30 20:58 UTC, chrisgarrity commented on src/editor/ui/UI.js
>              var sampleName = Localization.localize('SAMPLE_' + Project.metadata.name);
There is an issue with the project name localization. If the user changed the project name prior to making any other changes, the new name doesn't exist as a key `SAMPLE_<name>`, so the localization lookup fails. What ends up happening is the project name looks like "String missing: SAMPLE_<name>"

If they change the name after making changes everything is fine.

It could use `Localization.localizeOptional(...`, instead of `localize` but the returned string will be `SAMPLE_<name>`, so we'd still need to check for the `SAMPLE_` prefix and strip it off.

2021-07-31 02:34 UTC, yueyuzhao commented
There is another small issue that if you set the name to `Surprise` and return to the lobby, the name will be `Surprise 1` and it should be `Surprise`.

2021-08-02 14:26 UTC, chrisgarrity approved these changes
I wasn't sure it would make sense to add a `localizeSampleName` method, but I didn't realize how many places it's used. With this change it'll be more robust in future.

2021-08-02 14:26 UTC, merged