robust improvement: fix invalid input
LLK/scratchjr pull request #521
Opened 2021-10-05 13:35 UTC by yueyuzhao

### Resolves

- Resolves #509 

### Proposed Changes

When the block argument needs a number, set it to 0 if it's invalid.

### Reason for Changes

When editing running blocks, the single `-` sign is not processed properly. 

### Test Coverage

- [x] iPad mini 2 (iOS 12.5)
- [ ] Kindle Fire HD8 (Android 5.1)

2022-03-14 15:34 UTC, deepankarmalhan commented
SJR-158

2022-04-04 22:20 UTC, deepankarmalhan requested changes

2022-04-04 22:20 UTC, deepankarmalhan commented on src/editor/blocks/BlockArg.js
> +        if (this.argType == 'n' && isNaN(Number(val))) {
Why are we checking if a user enters the letter `n`?

2022-04-04 22:20 UTC, deepankarmalhan commented on src/editor/blocks/BlockArg.js
> +        if (this.argType == 'n' && isNaN(Number(val))) {
Also does this if statement make sure we don't stop the execution midway and keeps things running with the value 0? Has this been tested to see it doesn't remove character thumbnail from the project in the lobby?

2022-04-05 11:28 UTC, yueyuzhao commented on src/editor/blocks/BlockArg.js
> +        if (this.argType == 'n' && isNaN(Number(val))) {
> Why are we checking if a user enters the letter `n`?

`n` is an `argType`, we use `n` for `BlockArg` numbers

2022-04-05 11:29 UTC, yueyuzhao commented on src/editor/blocks/BlockArg.js
> +        if (this.argType == 'n' && isNaN(Number(val))) {
> Also does this if statement make sure we don't stop the execution midway and keeps things running with the value 0? 

Yes

> Has this been tested to see it doesn't remove character thumbnail from the project in the lobby?

I'll have this tested tomorrow.

2022-04-05 13:42 UTC, yueyuzhao commented on src/editor/blocks/BlockArg.js
> +        if (this.argType == 'n' && isNaN(Number(val))) {
I just tested this on the iOS simulator, the thumbnail of the project is generated fine.

2022-04-05 17:25 UTC, deepankarmalhan approved these changes

2022-04-05 17:25 UTC, merged