Android: check item path before unzipping
LLK/scratchjr pull request #545
Opened 2021-12-11 08:00 UTC by yueyuzhao

### Resolves

- Resolves https://github.com/LLK/scratchjr-private/issues/671

### Proposed Changes

Check item path before unzipping

### Reason for Changes

Please see https://support.google.com/faqs/answer/9294009 

### Test Coverage

- [x] Galaxy Tab A (Android 5.1.1)
- [x] Kindle Fire HD 8 (Android 5.1)
- [x] JD Tablet (Android 6.0)

2022-04-04 20:22 UTC, deepankarmalhan requested changes

2022-04-04 20:22 UTC, deepankarmalhan commented on android/ScratchJr/app/src/main/java/org/scratchjr/android/ScratchJrUtil.java
> +                    continue;
We should be throwing `SecurityException` here. Maybe instead of `continue;` we have `throw SecurityException("Unsafe file path found and unzipping will not be allowed for security purposes.");`

2022-04-05 17:40 UTC, deepankarmalhan commented
Have you testing this exception on a device?

2022-04-06 00:44 UTC, yueyuzhao commented
Yes, I tested this on Kindle Fire HD 8 with file [project-with-traverse-path-file.sjr.zip](https://github.com/LLK/scratchjr/files/8422688/project-with-traverse-path-file.sjr.zip) .
 There is a file named `../hello` with content `world` in it.

And I got the following log: 
```
2022-04-06 09:40:20.315 11712-11712/org.scratchjr.androidfree W/System.err: java.lang.SecurityException: Unsafe file path found and unzipping will not be allowed for security purposes.
```

2022-04-06 15:49 UTC, deepankarmalhan approved these changes

2022-04-06 15:49 UTC, merged